<?php
require_once __DIR__ . '/_bootstrap.php';

api_ok([
    'endpoints' => [
        'home' => '/api/home.php',
        'about' => '/api/about.php',
        'objectives' => '/api/objectives.php',
        'awards' => '/api/awards.php',
        'certificates' => '/api/certificates.php',
        'management' => '/api/management.php',
        'team' => '/api/team.php',
        'contact' => '/api/contact.php',
        'policies' => '/api/policies.php',
        'news' => '/api/news.php',
        'projects' => '/api/projects.php',
        'events' => '/api/events.php',
        'crowdfunding' => '/api/crowdfunding.php',
        'documents' => '/api/documents.php',
        'donate_options' => '/api/donate-options.php',
        'verify' => '/api/verify.php',
        'members' => '/api/members.php',
        'volunteers' => '/api/volunteers.php',
        'partners' => '/api/partners.php',
        'partner_info' => '/api/partner_info.php',
    ],
    'actions' => [
        'submit_contact' => '/api/submit_contact.php',
        'submit_inquiry' => '/api/submit_inquiry.php',
        'submit_donation' => '/api/submit_donation.php',
        'create_donation_order' => '/api/create_donation_order.php',
        'create_razorpay_order' => '/api/create_razorpay_order.php',
        'create_member_order' => '/api/create_member_order.php',
        'verify_razorpay_payment' => '/api/verify_razorpay_payment.php',
        'submit_member' => '/api/submit_member.php',
        'submit_volunteer' => '/api/submit_volunteer.php',
        'send_donor_otp' => '/api/send_donor_otp.php',
        'verify_donor_otp' => '/api/verify_donor_otp.php',
        'send_member_otp' => '/api/send_member_otp.php',
        'verify_member_otp' => '/api/verify_member_otp.php',
        'send_volunteer_otp' => '/api/send_volunteer_otp.php',
        'verify_volunteer_otp' => '/api/verify_volunteer_otp.php',
        'update_member_profile' => '/api/update_member_profile.php',
        'member_logout' => '/api/member_logout.php',
        'volunteer_logout' => '/api/volunteer_logout.php',
        'event_register' => '/api/event_register.php',
    ],
], 'NGO API is running.');
